name: gh-pages

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
      name: Build Docs
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          uses: actions/checkout@main
          with:
            # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
            fetch-depth: 0
        - uses: pnpm/action-setup@v2.0.1
          with:
            version: 6.20.3
        - name: Setup Node.js 16
          uses: actions/setup-node@v2
          with:
            node-version: 16
            cache: 'pnpm'
        - name: Install Dependencies
          run: pnpm install

        - name: Build & Make Docs
          run: |
              pnpm build
              mkdir docs
              mv packages/vue/docs docs/vue

        - name: Deploy docs
          if: github.event_name == 'push'
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: docs
